#!/bin/python3

from turtle import *
from random import randint #since we want to make the turtles move with random step at a time

#speed up the turtle to draw faster
speed(0)

#move the turtle to top-left instead but lift the pen up before
penup()
goto(-140,140)

for step in range(15):
    write(step, align = 'center')
    right(90)
    forward(10)
    pendown()
    forward(150)
    penup()
    backward(160)
    left(90)
    forward(20)


#Declaring the contenders
ada = Turtle()
ada.color('red')
ada.shape('turtle')

ada.penup()
ada.goto(-160, 100)
ada.pendown()

bob = Turtle()
bob.color('blue')
bob.shape('turtle')

bob.penup()
bob.goto(-160, 70)
bob.pendown()

bolt = Turtle()
bolt.color('yellow')
bolt.shape('turtle')

bolt.penup()
bolt.goto(-160, 40)
bolt.pendown()

#Contender racing
for turn in range(100):
    ada.forward(randint(1,5))
    bob.forward(randint(1,5))
    bolt.forward(randint(1,5))

